/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import eventadmin.ConnectSQLite;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author mariomena
 */
public class ExpositoresView extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form ExpositoresView
     */
    
    private addView add = new addView();
    
    
    public ExpositoresView() {
        initComponents();
        //Objeto para coneccion a base de datos
        ConnectSQLite sql = new ConnectSQLite();
        sql.ConsultaExpositoresList();//Genera la consulta de expositores.
        String[] expList = sql.getConsultaExpositores();//obtiene los nombres de los expositores en un array
        
        expositoresList.removeAllItems();//elimina los items por detafult en el ComboBox
        expositoresList.setModel(new javax.swing.DefaultComboBoxModel(expList));
        
        expTabb.addTab("Agregar Expositor", add);
        expTabb.setVisible(false);

    }
    
    public void setAddVisible(int i){
        if(i == 1){
            expTabb.setVisible(true);
        } else {
            expTabb.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        expositoresList = new javax.swing.JComboBox();
        giroLabel = new javax.swing.JLabel();
        respLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        modBtn = new javax.swing.JButton();
        remBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        expTabb = new javax.swing.JTabbedPane();

        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Expositor:");

        jLabel2.setText("Giro:");

        jLabel3.setText("Responsable:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Correo:");

        expositoresList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, expositoresList, org.jdesktop.beansbinding.ELProperty.create("${action.enabled}"), expositoresList, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        expositoresList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expositoresListActionPerformed(evt);
            }
        });

        addBtn.setText("Agregar");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        modBtn.setText("Modificar");

        remBtn.setText("Eliminar");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Consulta de Expositores");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jSeparator1))
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(expositoresList, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(mailLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(telLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, respLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(111, 111, 111)
                                        .add(giroLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))))))
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(addBtn)
                        .add(65, 65, 65)
                        .add(modBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 157, Short.MAX_VALUE)
                        .add(remBtn)
                        .add(25, 25, 25))
                    .add(layout.createSequentialGroup()
                        .add(94, 94, 94)
                        .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(expTabb))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(expositoresList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(54, 54, 54)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(giroLabel))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(respLabel))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(telLabel))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(mailLabel)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addBtn)
                    .add(modBtn)
                    .add(remBtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(expTabb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerDatos(String obD){
        ConnectSQLite sql = new ConnectSQLite();
        String[] expDat = new String[4];
        String[] expDatT = new String[4];
        expDatT = sql.getDatosExpositor(obD);
        if(obD != null){    
            for (int i = 0; i <= 3 ; i++){
                if(i < 3){
                expDat[i]=expDatT[i].toUpperCase();
                } else{
                    expDat[i]=expDatT[i];
                }
            }
        }
            
        if(expDat != null){ 
            giroLabel.setText(expDat[0]); 
            respLabel.setText(expDat[1]); 
            telLabel.setText(expDat[2]); 
            mailLabel.setText(expDat[3]); 
        } else{
            System.out.println("no hay datos");
        }
        
        
    }
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == addBtn){
            expTabb.setVisible(true);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void expositoresListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expositoresListActionPerformed

        if(evt.getSource() == expositoresList){
            String resp = (String)expositoresList.getSelectedItem();
            this.obtenerDatos(resp);
        }
    }//GEN-LAST:event_expositoresListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTabbedPane expTabb;
    private javax.swing.JComboBox expositoresList;
    private javax.swing.JLabel giroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JButton modBtn;
    private javax.swing.JButton remBtn;
    private javax.swing.JLabel respLabel;
    private javax.swing.JLabel telLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
